# Copyright 2021 METRO Digital GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build & Deploy master branch to PP environment
description: |-
  Build NodeJS code, run tests, perform SonarQube scan 
  and run semantic versioning
inputs:
  GITHUB_TOKEN:
    description: |-
      The GitHub specific token
    required: true
  SONAR_TOKEN:
    description: |-
      The SonarQube specific token
    required: true
  SONAR_HOST_URL:
    description: |-
      The SonarQube host URL
    required: true

outputs:
  release_version:
    description: |-
      The new version computed by semantic version system
    value: ${{ steps.msp-update-sonar-project-version.outputs.release_version }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js for release
      uses: actions/setup-node@v2
      with:
        node-version: "18"

    - name: Install Sonar .releaserc.js config file
      shell: bash
      run: cp ${{ github.action_path }}/sonar.releaserc.js .releaserc.js
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Install NodeSteps script
      shell: bash
      run: cp ${{ github.action_path }}/nodejs-steps.sh scripts/nodejs-steps.sh && chmod u+x scripts/nodejs-steps.sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: NodeJS build and run tests
      id: nodejs-build-and-test
      shell: bash
      run: scripts/nodejs-steps.sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Install SonarQube version updater
      shell: bash
      run: cp ${{ github.action_path }}/update-sonar-project-version.sh scripts/update-sonar-project-version.sh && chmod u+x scripts/update-sonar-project-version.sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Update SonarQube properties with project version
      id: update-sonar-project-version
      shell: bash
      run: scripts/update-sonar-project-version.sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: SonarQube scanner
      id: sonarqube-scan
      uses: docker://sonarsource/sonar-scanner-cli:latest
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}

    - name: Install CI .releaserc.js config file
      shell: bash
      run: cp ${{ github.action_path }}/ci.releaserc.js .releaserc.js
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Semantic Release
      id: semantic-release
      shell: bash
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

branding:
  color: yellow
  icon: code
